version: '2.1'

services:

  login-db:
    build: ./db
    environment:
      MYSQL_DATABASE: Ident
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      DATABASE_HOST: login-db

  login-ms:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: Ident
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - "3001:3000"
    depends_on:
      - login-db
    restart: on-failure
